In [359]:
import wrds
import pandas as pd

In [360]:
db = wrds.Connection()

WRDS recommends setting up a .pgpass file.
Created .pgpass file successfully.
Loading library list...
Done

In [361]:
tickers_compiled = ("A", "AACS", "AAIC", "AAIIQ", "AAL", "AAME", "AAM PR A", "AAN", "AAOI", "AAON", "AAP", "AAPL", "AASP", "AAT", "AATC", "AATV", "AAWW", "AB", "ABBB", "ABBY", "ABCB", "ABCP", "ABG", "ABLE", "ABM", "ABNB", "ABQQ", "ABR", "ABT", "AC", "ACA", "ACBCQ", "ACCO", "ACDC", "ACEL", "ACFN", "ACHR", "ACIW", "ACLS", "ACM", "ACMR", "ACMTA", "ACNB", "ACPS", "ACR", "ACRE", "ACRU", "ACT", "ACTG", "ACU", "ACVA", "ADBE", "ADC", "ADD", "ADEA", "ADEC", "ADFS", "ADGL", "ADGO", "ADI", "ADKT", "ADN", "ADP", "ADPT", "ADSK", "ADSV", "ADT", "ADTN", "ADVCD", "AE", "AEHR", "AEI", "AEIS", "AEL", "AENG", "AEO", "AERC", "AERG", "AERN", "AEVA", "AEY", "AEYE", "AFBI", "AFCG", "AFCL", "AFG", "AFHIF", "AFIIQ", "AFL", "AFRM", "AFTC", "AFTM", "AGAE", "AGCO", "AGDY", "AGFY", "AGIL", "AGM", "AGNC", "AGS", "AGTK", "AGX", "AGYS", "AHFI", "AHH", "AHT", "AI", "AIFM", "AIG", "AIMC", "AIN", "AINC", "AIP", "AIR", "AIRC", "AIRG", "AIRI", "AIRT", "AIT", "AIV", "AIZ", "AJG", "AJRD", "AJX", "AKA", "AKAM", "AKR", "AKTS", "AKVA", "AKYA", "AL", "ALBT", "ALBY", "ALEX", "ALFIQ", "ALG", "ALGM", "ALGT", "ALIT", "ALJJ", "ALK", "ALKT", "ALL", "ALLY", "ALMC", "ALME", "ALOD", "ALOT", "ALPE", "ALPIB", "ALPP", "ALRM", "ALRS", "ALSN", "ALTD", "ALTG", "ALTO", "ALTR", "ALTX", "ALX", "ALYI", "AM", "AMAL", "AMAT", "AMBA", "AMBC", "AMBK", "AMBZ", "AMD", "AME", "AMEN", "AMFC", "AMG", "AMH", "AMHG", "AMIN", "AMK", "AMKR", "AMLC", "AMMX", "AMNB", "AMOT", "AMP", "AMPG", "AMPL", "AMPX", "AMPY", "AMRA", "AMRC", "AMRK", "AMRT", "AMSC", "AMSF", "AMST", "AMSWA", "AMT", "AMTA", "AMTB", "AMTX", "AMTY", "AMV", "AMWD", "AMWK", "AMXX", "AMZN", "AN", "ANAS", "ANDC", "ANDR", "ANET", "ANF", "ANSS", "ANVV", "AOMR", "AOS", "AOSL", "AOUT", "AOXY", "APA", "APAM", "APCX", "APDN", "APEI", "APG", "APGI", "APGT", "APH", "APHD", "APHE", "APLD", "APLE", "APLN", "APO", "APOG", "APP", "APPF", "APPN", "APPS", "APPZ", "APTY", "APVS", "AQMS", "AQQSQ", "AQUA", "AR", "ARAO", "ARBV", "ARC", "ARC", "ARCB", "ARCC", "ARCH", "ARCS", "ARCW", "ARE", "AREB", "AREC", "ARES", "ARET", "ARGL", "ARHN", "ARHS", "ARI", "ARIS", "ARKO", "ARKR", "ARL", "ARLO", "ARLP", "ARMK", "AROC", "AROW", "ARR", "ARRY", "ARSC", "ARTW", "ARW", "ARWD", "ARYC", "ASAN", "ASAP", "ASB", "ASDN", "ASGN", "ASLE", "ASNS", "ASO", "ASPU", "ASPW", "ASPZ", "ASRV", "ASTC", "ASTE", "ASTI", "ASTR", "ASUR", "ASYS", "ATAR", "ATAX", "ATCN", "ATCX", "ATDS", "ATEN", "ATER", "ATGE", "ATGN", "ATKR", "ATLC", "ATLO", "ATMO", "ATNP", "ATOM", "ATRO", "ATSG", "ATVK", "ATWT", "ATYG", "AUB", "AUBN", "AUID", "AUR", "AURI", "AUSI", "AUUD", "AUVI", "AVAV", "AVB", "AVBH", "AVCT", "AVDX", "AVEW", "AVGO", "AVID", "AVNE", "AVNW", "AVOA", "AVOI", "AVOT", "AVPT", "AVRI", "AVSR", "AVT", "AVTR", "AVYA", "AWAW", "AWI", "AWON", "AWRE", "AWRS", "AWX", "AX", "AXAS", "AXGC", "AXL", "AXON", "AXP", "AXP", "AXPT", "AXPWQ", "AXR", "AXTG", "AXTI", "AYI", "AYRO", "AYX", "AZDDQ", "AZEK", "AZGSQ", "AZIL", "AZO", "AZPN", "AZRH", "AZTA", "AZZ", "B", "BA", "BABB", "BAC", "BAFI", "BAFN", "BAH", "BALY", "BANC", "BANF", "BANI", "BANR", "BANT", "BANX", "BAOB", "BARK", "BASE", "BATL", "BBAI", "BBBK", "BBBY", "BBCP", "BBDC", "BBRW", "BBSI", "BBUC", "BBW", "BBWI", "BBXIA", "BBY", "BC", "BCAL", "BCAP", "BCBP", "BCC", "BCCI", "BCDS", "BCII", "BCML", "BCNN", "BCO", "BCOR", "BCOV", "BCOW", "BCRD", "BCSF", "BCSO", "BCTF", "BDC", "BDCO", "BDGR", "BDGY", "BDL", "BDN", "BDRL", "BDVB", "BEBE", "BECN", "BEEM", "BEEN", "BEGI", "BELFA", "BEN", "BEOB", "BETW", "BFAM", "BFC", "BFCH", "BFH", "BFI", "BFIN", "BFS", "BFST", "BFYW", "BGCP", "BGFV", "BGMD", "BGRP", "BGRY", "BGSF", "BH.A", "BHB", "BHBCQ", "BHE", "BHF", "BHG", "BHLB", "BHM", "BHPA", "BHR", "BHRB", "BHWB", "BICB", "BIG", "BIGC", "BIGG", "BILL", "BIO", "BIOF", "BIRD", "BJRI", "BK", "BKCC", "BKE", "BKFG", "BKI", "BKKT", "BKNG", "BKOR", "BKR", "BKSC", "BKSH", "BKSY", "BKTI", "BKU", "BKUT", "BKYI", "BL", "BLBD", "BLBX", "BLD", "BLDE", "BLDR", "BLFS", "BLFY", "BLHI", "BLHK", "BLI", "BLIN", "BLK", "BLKB", "BLMC", "BLMN", "BLND", "BLNK", "BLPG", "BLZE", "BMBN", "BMI", "BMNM", "BMNR", "BMRC", "BMTX", "BMXC", "BNCC", "BNED", "BNET", "BNFT", "BNGI", "BNGO", "BNL", "BNXR", "BODY", "BOH", "BOID", "BOKF", "BOKU", "BOLL", "BOMO", "BONL", "BONTQ", "BOOM", "BOOT", "BOPO", "BORT", "BOTJ", "BOWL", "BOX", "BOXD", "BOXL", "BPCP", "BPOL", "BPRN", "BPT", "BR", "BRAV", "BRBL", "BRBS", "BRBW", "BRC", "BRDG", "BRDS", "BRER", "BRGO", "BRK.A", "BRKL", "BRKR", "BRLT", "BRMK", "BRN", "BRO", "BROS", "BRP", "BRRE", "BRSI", "BRSP", "BRST", "BRT", "BRX", "BRY", "BRZE", "BSBK", "BSET", "BSHI", "BSIG", "BSM", "BSPA", "BSQR", "BSRR", "BSTK", "BSVN", "BSY", "BTBD", "BTBT", "BTCS", "BTOG", "BTRS", "BTSR", "BTU", "BUKS", "BULT", "BURCA", "BURL", "BUSE", "BV", "BVFL", "BVH", "BVTK", "BW", "BWA", "BWB", "BWEN", "BWFG", "BWLK", "BWMG", "BWMN", "BWPC", "BWTL", "BWXT", "BX", "BXC", "BXLC", "BXMT", "BXP", "BXSL", "BY", "BYD", "BYFC", "BYLB", "BYRN", "BZH", "BZIC", "BZRD", "BZWR", "C", "CAC", "CACC", "CACH", "CACI", "CADE", "CAFI", "CAGR", "CAGU", "CAHI", "CAKE", "CAL", "CALB", "CALX", "CAMP", "CANN", "CANX", "CAPC", "CAPL", "CAR", "CARE", "CARR", "CARV", "CASA", "CASH", "CASS", "CAT", "CATC", "CATI", "CATO", "CATY", "CAVR", "CBAN", "CBCY", "CBDG", "CBFV", "CBGH", "CBGI", "CBHR", "CBKCQ", "CBKM", "CBL", "CBMI", "CBNK", "CBOBA", "CBOE", "CBRE", "CBRI", "CBRL", "CBSH", "CBU", "CBWA", "CBYI", "CBZ", "CCAP", "CCB", "CCBC", "CCBG", "CCCS", "CCFC", "CCFN", "CCI", "CCL", "CCLP", "CCNE", "CCRD", "CCS", "CCSI", "CCTC", "CCTL", "CCTR", "CCUR", "CDAY", "CDFT", "CDID", "CDIIQ", "CDNS", "CDRBQ", "CDRE", "CDTI", "CDVIQ", "CDW", "CDXC", "CDXS", "CEAD", "CECO", "CEFC", "CEI", "CEIX", "CENN", "CEOA", "CEQP", "CERX", "CESX", "CETX", "CETY", "CEVA", "CEVE", "CEXE", "CFB", "CFBK", "CFCI", "CFCX", "CFFI", "CFFN", "CFG", "CFGX", "CFIC", "CFLT", "CFNB", "CFOK", "CFR", "CFSB", "CFST", "CG", "CGAC", "CGBD", "CGIP", "CGLO", "CGNX", "CGRA", "CGRN", "CGRW", "CGUD", "CHAM", "CHBH", "CHCI", "CHCO", "CHCT", "CHDN", "CHFI", "CHGG", "CHH", "CHIT", "CHK", "CHKR", "CHMG", "CHMI", "CHMP", "CHMR", "CHMX", "CHPT", "CHRA", "CHRD", "CHRW", "CHS", "CHSH", "CHTH", "CHUY", "CHWY", "CHX", "CIA", "CIBH", "CIBN", "CICN", "CIEN", "CIFR", "CIM", "CINF", "CIO", "CION", "CIPI", "CIR", "CISO", "CITY", "CITZ", "CIVB", "CIVI", "CIWV", "CIX", "CIZN", "CKCB", "CKX", "CLAR", "CLBK", "CLDT", "CLFD", "CLH", "CLHI", "CLIR", "CLIS", "CLMB", "CLMT", "CLNE", "CLNV", "CLOQ", "CLOW", "CLPE", "CLPR", "CLRI", "CLRO", "CLSK", "CLST", "CLTH", "CLUBQ", "CLWY", "CMA", "CMBM", "CMCO", "CMCT", "CME", "CMFV", "CMG", "CMHF", "CMI", "CMPO", "CMTG", "CMTL", "CMTV", "CMUV", "CNA", "CNAF", "CNBA", "CNBB", "CNBN", "CNBW", "CNBZ", "CNCN", "CNDD", "CNDT", "CNFR", "CNGO", "CNGT", "CNM", "CNNB", "CNND", "CNNE", "CNO", "CNO", "CNOB", "CNRD", "CNS", "CNTO", "CNTY", "CNUN", "CNVT", "CNWT", "CNX", "CNXA", "CNXC", "CNXN", "CNXS", "COCM", "CODA", "CODI", "COF", "COFE", "COFS", "COHN", "COHR", "COHU", "CONTININS", "COIN", "COLB", "COLD", "COLM", "COMM", "COMP", "COMS", "CONC", "CONN", "COOK", "COOP", "COP", "CORG", "CORR", "CORZ", "COUP", "COUR", "COWI", "COWN", "COWP", "CPE", "CPF", "CPHC", "CPKF", "CPMV", "CPNG", "CPRT", "CPS", "CPSH", "CPSS", "CPT", "CPTN", "CPTP", "CPYJ", "CQP", "CR", "CRAI", "CRAWA", "CRBG", "CRBO", "CRC", "CRCT", "CRCW", "CRD.B", "CRDE", "CRDV", "CRFU", "CRGY", "CRI", "CRK", "CRKR", "CRKT", "CRL", "CRLI", "CRM", "CRMT", "CRMZ", "CRNC", "CROX", "CRRSQ", "CRSB", "CRSR", "CRT", "CRTG", "CRUS", "CRWD", "CRWS", "CRZY", "CSBB", "CSBI", "CSBR", "CSCO", "CSGP", "CSGS", "CSHX", "CSL", "CSLI", "CSPI", "CSR", "CSSV", "CSTI", "CSTR", "CSV", "CSWC", "CSWI", "CSX", "CSYT", "CTAM", "CTAS", "CTBI", "CTCC", "CTG", "CTHR", "CTIB", "CTKB", "CTLP", "CTM", "CTNR", "CTO", "CTOS", "CTPR", "CTRA", "CTRE", "CTRN", "CTS", "CTSH", "CTUY", "CTXV", "CUBE", "CUBI", "CULL", "CULP", "CURO", "CURV", "CUZ", "CVAT", "CVBF", "CVCO", "CVCY", "CVEO", "CVGI", "CVHL", "CVI", "CVLG", "CVLT", "CVLY", "CVNA", "CVR", "CVT", "CVU", "CVV", "CVX", "CW", "CWAN", "CWBC", "CWBK", "CWH", "CWST", "CXCQ", "CXDC", "CXDO", "CXI", "CXIA", "CXM", "CXW", "CYAP", "CYBA", "CYBD", "CYBF", "CYBL", "CYCA", "CYFL", "CYGT", "CYN", "CYPE", "CYRS", "CYRX", "CYSM", "CYXT", "CYZN", "CZBC", "CZBS", "CZBT", "CZFS", "CZNB", "CZNC", "CZNL", "CZR", "CZWI", "DAAT", "DAIO", "DAKT", "DAL", "DAN", "DASH", "DATS", "DAVE", "DBD", "DBGI", "DBI", "DBIN", "DBMG", "DBRG", "DBRM", "DBX", "DCAC", "DCI", "DCO", "DCOM", "DCP", "DCT", "DDD", "DDDX", "DDOG", "DDS", "DE", "DEA", "DEC", "DECK", "DEI", "DELL", "DEN", "DENN", "DENR", "DESTQ", "DEVM", "DEWY", "DFCO", "DFH", "DFIN", "DFLI", "DFS", "DFTC", "DG", "DGICA", "DGIF", "DGII", "DGIX", "DGLY", "DGWR", "DHC", "DHI", "DHIL", "DHR", "DIBS", "DIGI", "DIMC", "DIN", "DINO", "DIOD", "DION", "DIT", "DK", "DKGH", "DKGR", "DKL", "DKNG", "DKS", "DLA", "DLAD", "DLB", "DLGI", "DLHC", "DLPX", "DLR", "DLTH", "DLTR", "DLX", "DLYT", "DM", "DMC", "DMCD", "DMEC", "DMFG", "DMLP", "DMRC", "DNAY", "DNB", "DNOW", "DNUT", "DO", "DOC", "DOCN", "DOCU", "DOMA", "DOMO", "DOMR", "DOOR", "DORM", "DOUG", "DOV", "DOX", "DPLS", "DPSI", "DPZ", "DRH", "DRI", "DRQ", "DRVN", "DRYN", "DS", "DSBX", "DSGR", "DSKE", "DSP", "DSRO", "DSS", "DSUS", "DT", "DTC", "DTII", "DTM", "DTSL", "DTST", "DUOL", "DUOT", "DV", "DVC.H", "DVLN", "DVN", "DWAY", "DWIS", "DWNX", "DWSN", "DX", "DXC", "DXLG", "DXPE", "DXYN", "DY", "DYNE", "DYSL", "DZSI", "EACC", "EACO", "EAF", "EARN", "EAT", "EATR", "EAUI", "EAWD", "EAXR", "EBAY", "EBC", "EBET", "EBF", "EBIX", "EBMT", "EBTC", "EBWK", "EBYH", "EBZT", "ECBK", "ECCE", "ECCI", "ECDD", "ECMH", "ECPG", "ECRO", "ECT", "ECTM", "EDHD", "EDMCQ", "EDTA", "EDUC", "EE", "EEFT", "EEGI", "EEIQ", "EESH", "EFBI", "EFC", "EFIN", "EFIR", "EFOI", "EFSC", "EFSH", "EFSI", "EFTI", "EFV", "EFX", "EGAN", "EGBN", "EGHT", "EGIL", "EGIO", "EGLE", "EGP", "EGTK", "EGY", "EHTH", "EHYD", "EIG", "EKCS", "ELA", "ELCO", "ELCR", "ELEK", "ELGL", "ELIO", "ELMA", "ELME", "ELMSQ", "ELRA", "ELS", "ELSE", "ELST", "ELVT", "EMAN", "EMBK", "EMCF", "EME", "EMHI", "EMKR", "EML", "EMNC", "EMPS", "EMQU", "EMR", "EMYB", "ENBP", "ENCC", "ENCR", "ENCS", "ENDI", "ENFN", "ENG", "ENGT", "ENGY", "ENHT", "ENJYQ", "ENLC", "ENPH", "ENS", "ENSV", "ENTG", "ENV", "ENVA", "ENVS", "ENVX", "EOG", "EOSE", "EP", "EPAC", "EPAM", "EPAZ", "EPD", "EPEO", "EPM", "EPOR", "EPR", "EPRT", "EPSN", "EP PR C", "EQBK", "EQC", "EQFN", "EQH", "EQIX", "EQR", "EQS", "EQT", "EQUR", "ERAO", "ERHE", "ERIE", "ERII", "ERINQ", "ERKH", "ESAB", "ESBA", "ESCA", "ESE", "ESINQ", "ESMT", "ESNC", "ESNR", "ESOA", "ESP", "ESQ", "ESQF", "ESRT", "ESS", "ESSA", "ESTE", "ESWW", "ET", "ETCC", "ETCIA", "ETD", "ETII", "ETRN", "ETSY", "ETWO", "EU", "EVA", "EVBG", "EVBN", "EVCI", "EVCM", "EVEX", "EVGO", "EVI", "EVIO", "EVLV", "EVOA", "EVOL", "EVOP", "EVR", "EVRC", "EVRI", "EVSP", "EVSV", "EVTN", "EVTV", "EWBC", "EWCZ", "EXBX", "EXCC", "EXCE", "EXCH", "EXEO", "EXFY", "EXLS", "EXPD", "EXPE", "EXPH", "EXPI", "EXPO", "EXPR", "EXR", "EXSO", "EXSR", "EXTR", "EYE", "EZEN", "EZFL", "EZPW", "F", "FA", "FABP", "FACO", "FAF", "FALC", "FANG", "FARO", "FAST", "FAT", "FATH", "FAVO", "FBAK",  "FBCE", "FBGI", "FBHS", "FBIP", "FBIZ", "FBK", "FBMS", "FBNC", "FBOO", "FBPA", "FBPI", "FBRT", "FBSE", "FBSI", "FBTT", "FC", "FCAP", "FCBC", "FCCN", "FCCO", "FCEL", "FCF", "FCFS", "FCGY", "FCIT", "FCN", "FCNCA", "FCNCO", "FCNE", "FCOB", "FCPB", "FCPT", "FCRD", "FCRM", "FCUV", "FDBC", "FDBH", "FDCT", "FDEI", "FDHC", "FDLB", "FDOC", "FDS", "FDUS", "FDVA", "FDX", "FEIM", "FELE", "FET", "FETM", "FFBC", "FFBW", "FFDF", "FFIC", "FFIE", "FFIN", "FFIV", "FFMH", "FFMR", "FFNW", "FFPM", "FFWM", "FGBI", "FGF", "FGFH", "FGI", "FHB", "FHI", "FHN", "FHRT", "FIBK", "FICO", "FIGR", "FINN", "FINW", "FIP", "FIS", "FISB", "FISI", "FISV", "FITB", "FIVE", "FIVN", "FIX", "FIZN", "FKWL", "FKYS", "FL", "FLC", "FLFG", "FLIC", "FLL", "FLNC", "FLR", "FLRZ", "FLS", "FLST", "FLT", "FLUX", "FLWS", "FLXI", "FLXP", "FLXS", "FLXT", "FLYW", "FMAO", "FMBH", "FMBL", "FMBM", "FMBN", "FMCB", "FMCC", "FMFG", "FMFP", "FMIA", "FMNB", "FMOO", "FNB", "FNCB", "FND", "FNF", "FNFI", "FNHC", "FNKO", "FNLC", "FNMA", "FNRC", "FNRG", "FNRN", "FNWB", "FNWD", "FOA", "FOCS", "FOR", "FORD", "FORG", "FORM", "FORR", "FOSL", "FOTB", "FOUR", "FOXF", "FOXO", "FPAY", "FPH", "FPI", "FPPP", "FR", "FRAF", "FRBA", "FRBK", "FRC", "FREVS", "FRFC", "FRG", "FRGE", "FRGI", "FRGT", "FRGY", "FRHC", "FRMB", "FRMC", "FRME", "FROG", "FRPH", "FRSB", "FRSH", "FRST", "FRT", "FRTD", "FRTN", "FRXX", "FRZA", "FSBC", "FSBW", "FSCR", "FSDK", "FSEA", "FSEI", "FSFG", "FSGB", "FSK", "FSLR", "FSLY", "FSP", "FSR", "FSRDQ", "FSRL", "FSS", "FSTR", "FSWA", "FTAI", "FTCI", "FTDL", "FTDR", "FTEK", "FTFT", "FTHM", "FTNT", "FTV", "FULT", "FUN", "FUNC", "FUSB", "FUTL", "FUV", "FVCB", "FWRD", "FWRG", "FXLG", "FXLV", "FXNC", "GABA", "GABC", "GACR", "GADS", "GAEC", "GAEX", "GAHC", "GAIN", "GAMI", "GAN", "GARB", "GASE", "GATX", "GAWK", "GAXY", "GBCI", "GBCS", "GBDC", "GBLI", "GBNY", "GBR", "GBTG", "GBX", "GCBC", "GCEI", "GCFB", "GCHK", "GCMG", "GCO", "GD", "GDDY", "GDEN", "GDOT", "GDSI", "GDYN", "GE", "GECC", "GEGR", "GEL", "GELV", "GEN", "GENC", "GEO", "GEOS", "GEPC", "GERS", "GES", "GEVO", "GFCJ", "GFF", "GFGU", "GFGY", "GFS", "GFTX", "GGBL", "GGG", "GGII", "GGLT", "GHC", "GHL", "GHLD", "GHM", "GIBX", "GIC", "GIFI", "GIGA", "GIII", "GIPL", "GIPR", "GKIN", "GKIT", "GL", "GLAD", "GLAE", "GLBR", "GLBZ", "GLCO", "GLDD", "GLEC", "GLFN", "GLP", "GLPI", "GLPT", "GLRI", "GLRP", "GLW", "GLXY", "GLXZ", "GM", "GME", "GMEI", "GMND", "GMNI", "GMPR", "GMRE", "GMS", "GNAL", "GNK", "GNL", "GNLN", "GNOLF", "GNRC", "GNRD", "GNRV", "GNSS", "GNTX", "GNTY", "GNW", "GOCH", "GOCO", "GOEV", "GOGRID SDB", "GOLF", "GOOD", "GOVB", "GPC", "GPGC", "GPI", "GPKE", "GPMT", "GPN", "GPOR", "GPP", "GPRE", "GPRO", "GPS", "GPTC", "GPTX", "GQG", "GRBK", "GRC", "GREE", "GRGR", "GRIL", "GRLT", "GRNT", "GROV", "GROW", "GRPN", "GRPX", "GRRB", "GRWC", "GRWG", "GS", "GSBC", "GSBD", "GSBX", "GSFI", "GSHD", "GSIT", "GSPE", "GSPH", "GSPT", "GSVI", "GSW", "GT", "GTCH", "GTCP", "GTEC", "GTES", "GTGP", "GTII", "GTIM", "GTLB", "GTLS", "GTPS", "GTTNQ", "GTY", "GULTU", "GVA", "GVP", "GVSI", "GWAV", "GWGHQ", "GWH", "GWRE", "GWTI", "GWW", "GWYT", "GXO", "GYOG", "GYRO", "H", "HA", "HABK", "HAFC", "HAL", "HALL", "HALN", "HARL", "HAS", "HASI", "HAUP", "HAYW", "HAZH", "HBAN", "HBB", "HBCP", "HBI", "HBIA", "HBIE", "HBIO", "HBNC", "HBSI", "HBT", "HCBC", "HCBN", "HCCI", "HCDI", "HCGI", "HCI", "HCKT", "HCP", "HCSG", "HD", "HDSN", "HDYNQ", "HEAR", "HEES", "HEI", "HENC", "HEOL", "HEP", "HERC", "HES", "HESM", "HESV", "HEWA", "HFBA", "HFBK", "HFBL", "HFUS", "HFWA", "HGBL", "HGGGQ", "HGLC", "HGTXU", "HGTY", "HGV", "HHC", "HHDS", "HHER", "HI", "HIBB", "HIFS", "HIG", "HIHI", "HII", "HIL", "HIMR", "HIPO", "HIW", "HLAN", "HLBYL", "HLBZ", "HLFN", "HLGN", "HLI", "HLIO", "HLIT", "HLLY", "HLMN", "HLNE", "HLOC", "HLT", "HLX", "HLXW", "HMBL", "HMLN", "HMN", "HMNF", "HMNU", "HMNY", "HMPT", "HMST", "HNI", "HNNA", "HNRC", "HNRG", "HNVR", "HOFT", "HOFV", "HOG", "HOKUQ", "HOMB", "HOM.U", "HON", "HONE", "HONT", "HOOB", "HOOD", "HOPE", "HOUR", "HOUS", "HOV", "HP", "HPE", "HPIL", "HPK", "HPNN", "HPP", "HPQ", "HPST", "HPTO", "HQI", "HR", "HRB", "HRBR", "HRGG", "HRI", "HRST", "HRT", "HRTG", "HRZN", "HSBI", "HSC", "HSII", "HSON", "HST", "HT", "HTBI", "HTBK", "HTDS", "HTGC", "HTH", "HTIA", "HTLD", "HTLF", "HTRE", "HTSC", "HTZ", "HUBB", "HUBG", "HUBS", "HUBV", "HURC", "HURN", "HUSA", "HVBC", "HVCW", "HVT", "HWBK", "HWC", "HWM", "HWNI", "HWSY", "HXL", "HY", "HYDN", "HYEG", "HYFM", "HYGN", "HYLN", "HYRE", "HYSR", "HYZN", "HZHI", "HZN", "HZO", "IAA", "IAHL", "IBCP", "IBEX", "IBGR", "IBIN", "IBKR", "IBM", "IBOC", "IBP", "IBRC", "IBSS", "IBTN", "IBTX", "ICBT", "ICBU", "ICCH", "ICD", "ICE", "ICFI", "ICHR", "ICLD", "ICMB", "ICNM", "ICRD", "ICR PR A", "ID", "IDAI", "IDCC", "IDEA", "IDEX", "IDN", "IEHC", "IEP", "IESC", "IEX", "IEXA", "IFNY", "IFXY", "IGC", "IGEN", "IGPG", "IGPK", "IHT", "IHTI", "III", "IIIN", "IIIV", "IIPR", "IJJP", "ILAL", "ILMN", "ILPT", "IMBI", "IMCI", "IMH", "IMJN", "IMMR", "IMP", "IMTL", "IMXI", "INAR", "INBK", "INDB", "INDI", "INDT", "INFA", "INFN", "INIS", "INIX", "INLX", "INN", "INNI", "INNX", "INOD", "INOH", "INPX", "INRD", "INSE", "INSG", "INSO", "INST", "INSW", "INT", "INTA", "INTC", "INTG", "INTT", "INTU", "INTV", "INTZ", "INUV", "INVE", "INVH", "INVI", "INVU", "IONQ", "IOR", "IOT", "IPGP", "IPIC", "IPW", "IPWG", "IPWR", "IQV", "IR", "IRBL", "IRBT", "IRIG", "IRM", "IRNT", "IROQ", "IRT", "ISBA", "ISDR", "ISGN", "ISHI", "ISO", "ISON", "ISPD", "ISPO", "ISSC", "ISTR", "ISUN", "IT", "ITEX", "ITI", "ITIC", "ITLI", "ITNM", "ITPC", "ITRI", "ITT", "ITW", "IVAC", "IVDA", "IVDN", "IVR", "IVT", "IVZ", "IWSY", "IXEH", "IXOG", "J", "JACK", "JACO", "JADA", "JAGR", "JAKK", "JALC", "JAMF", "JAN", "JANL", "JBGS", "JBHT", "JBI", "JBL", "JBLU", "JBT", "JBTC", "JCTCF", "JDVB", "JEF", "JELD", "JERT", "JET", "JFBC", "JFWV", "JILL", "JKHY", "JKSM", "JLL", "JLMC", "JMIH", "JMON", "JMSB", "JNPR", "JOAN", "JOB", "JOBY", "JOE", "JOUT", "JPEX", "JPM", "JRJRQ", "JRSH", "JRVS", "JUVF", "JWN", "JXN", "KAHL", "KAI", "KAMN", "KANP", "KAR", "KARE", "KASH", "KAVL", "KBAL", "KBH", "KBPH", "KBR", "KBSR", "KCLI", "KD", "KE", "KED", "KEGX", "KEI", "KELYA", "KENS", "KERN", "KEX", "KEY", "KEYS", "KFFB", "KFRC", "KFS", "KFY", "KGET", "KGHI", "KIDBQ", "KIM", "KINS", "KIRK", "KISB", "KITL", "KITT", "KKR", "KLAC", "KLDI", "KLIB", "KLNG", "KLR", "KLTR", "KLXE", "KMFI", "KMI", "KMPR", "KMT", "KMX", "KN", "KNBA", "KNBE", "KNOS", "KNSL", "KNTK", "KNX", "KODK", "KOLR", "KOPN", "KOS", "KOSK", "KOSS", "KPLT", "KRC", "KREF", "KRG", "KRNY", "KRP", "KRT", "KRUS", "KSBI", "KSCP", "KSPN", "KSS", "KTB", "KTCC", "KTHN", "KTOS", "KULR", "KVHI", "KVIL", "KW", "KWIK", "L", "LAB", "LAD", "LADR", "LAKE", "LAMR", "LAND", "LARK", "LASE", "LASR", "LAUR", "LAW", "LAXAF", "LAZR", "LAZY", "LBAI", "LBAS", "LBC", "LBRT", "LBYE", "LC", "LCID", "LCII", "LCNB", "LCNTU", "LCTC", "LCUT", "LDI", "LDOS", "LE", "LEA", "LEAI", "LEAS", "LECO", "LEG", "LEGH", "LEK", "LEN", "LEON", "LESL", "LEU", "LEVI", "LFAP", "LFER", "LFEV", "LFG", "LFGP", "LFIN", "LFT", "LFUS", "LGIH", "LGIQ", "LGL", "LHX", "LICH", "LIDR", "LII", "LINC", "LIND", "LINK", "LIQDQ", "LITE", "LIVC", "LIVE", "LKCRU", "LKFN", "LKQ", "LL", "LLAP", "LMB", "LME", "LMFA", "LMND", "LMPX", "LMST", "LMT", "LMTI", "LNC", "LNDT", "LNG", "LNKB", "LNKG", "LNN", "LNW", "LOAN", "LOB", "LOCO", "LODE", "LOGL", "LOGN", "LOPE", "LOTZ", "LOVE", "LOW", "LPG", "LPI", "LPLA", "LPPI", "LPRO", "LPSN", "LPTH", "LQDT", "LRBI", "LRCX", "LRDC", "LRFC", "LRN", "LSBK", "LSCC", "LSCG", "LSEA", "LSFG", "LSI", "LSKA", "LSTR", "LTBR", "LTC", "LTCH", "LTCP", "LTEC", "LTFD", "LTH", "LTHUQ", "LTRE", "LTRX", "LTRY", "LTTC", "LUNA", "LUV", "LUXH", "LVLU", "LVLV", "LVOX", "LVPA", "LVS", "LVWR", "LWCL", "LWLG", "LXP", "LYBC", "LYFT", "LYTS", "LZ", "LZB", "M", "MA", "MAA", "MAAL", "MAC", "MACE", "MAIN", "MAJJ", "MAN", "MANH", "MAPS", "MAPS", "MAPT", "MAR", "MARA", "MARK", "MARPS", "MAS", "MASS", "MAT", "MATW", "MATX", "MAXD", "MAXR", "MAYS", "MBCN", "MBI", "MBIN", "MBKL", "MBLV", "MBUU", "MBVA", "MBWM", "MC", "MCAP", "MCB", "MCBC", "MCBI", "MCBK", "MCBS", "MCCK", "MCD", "MCFT", "MCG", "MCHB", "MCHP", "MCHT", "MCIM", "MCO", "MCPH", "MCRAA", "MCRI", "MCVT", "MCW", "MCY", "MDB", "MDC", "MDLM", "MDMP", "MDRA", "MDRR", "MDU", "MDV", "MDVT", "MDWT", "MEC", "MEDH", "MEDP", "MEDS", "MEDT", "MEEC", "MEG", "MEI", "MEIL", "MERG", "MERR", "MESA", "MET", "MFA", "MFBP", "MFCO", "MFGI", "MFIC", "MFIN", "MG", "MGHL", "MGI", "MGLG", "MGLO", "MGM", "MGRC", "MGTI", "MGY", "MGYR", "MHC.U", "MHGI", "MHGU", "MHH", "MHHC", "MHK", "MHO", "MHPC", "MHYR", "MICS", "MICT", "MIDD", "MIFF", "MIMO", "MIND", "MINM", "MIR", "MIRO", "MITK", "MITT", "MJWL", "MKFG", "MKL", "MKSI", "MKTW", "MKTX", "ML", "MLGF", "MLI", "MLKN", "MLNK", "MLP", "MLR", "MLRT", "MLVF", "MMC", "MMEX", "MMI", "MMIO", "MMLP", "MMM", "MMMW", "MMP", "MMS", "MMTC", "MMTS", "MNAT", "MNBP", "MNDP", "MNII", "MNLX", "MNMB", "MNPP", "MNRL", "MNRO", "MNSB", "MNTS", "MNTV", "MNTX", "MNVN", "MOD", "MODC", "MODG", "MODN", "MOFG", "MOG.A", "MOMT", "MOND", "MORN", "MOV", "MOVE", "MPAA", "MPAD", "MPB", "MPC", "MPIR", "MPLX", "MPML", "MPTI", "MPW", "MPWR", "MPX", "MQ", "MRAI", "MRAM", "MRBK", "MRC", "MRCC", "MRCY", "MRGE", "MRIB", "MRIN", "MRO", "MRTI", "MRTN", "MRVI", "MRVL", "MS", "MSA", "MSBC", "MSBI", "MSCI", "MSFT", "MSI", "MSM", "MSN", "MSSV", "MSTR", "MSVB", "MTB", "MTD", "MTDR", "MTG", "MTH", "MTMT", "MTN", "MTNX", "MTR", "MTRT", "MTRX", "MTSI", "MTST", "MTTR", "MTW", "MTZ", "MU", "MUEL", "MULN", "MUR", "MUSA", "MUSS", "MVAC", "MVBF", "MVIS", "MVLY", "MVO", "MVST", "MWA", "MWRK", "MWWC", "MXC", "MXCT", "MXL", "MYBF", "MYFW", "MYRG", "MYX", "NABL", "NACB", "NASB", "NATH", "NATI", "NAUH", "NAUT", "NAVI", "NBDR", "NBHC", "NBN", "NBTB", "NBVA", "NC", "NCLH", "NCNO", "NCPL", "NCR", "NCRA", "NCSM", "NCXS", "NDAQ", "NDEV", "NDLS", "NDSN", "NDVNQ", "NE", "NECB", "NEFB", "NEGG", "NEN", "NEO", "NEOM", "NEOV", "NEPH", "NESR", "NET", "NEWH", "NEWR", "NEWT", "NEX", "NEXT", "NFBK", "NFE", "NFEI", "NFSE", "NGL", "NGL", "NGS", "NHHS", "NHI", "NHLI", "NIC", "NICH", "NICK", "NIDB", "NIHK", "NILE", "NINE", "NKE", "NKLA", "NKSH", "NL", "NLCP", "NLS", "NLST", "NLY", "NMEX", "NMFC", "NMGC", "NMIH", "NMRK", "NMSCA", "NN", "NNBR", "NNFC", "NNI", "NNN", "NNRI", "NOBH", "NOC", "NODB", "NODK", "NOG", "NOGN", "NOTE", "NOTV", "NOV", "NOVT", "NOW", "NOXL", "NPK", "NPO", "NR", "NRDS", "NRDY", "NREF", "NRGT", "NRGV", "NRIM", "NRIS", "NRLB", "NROM", "NRP", "NRT", "NS", "NSA", "NSC", "NSIT", "NSLPQ", "NSP", "NSSC", "NSTG", "NSTS", "NSYS", "NTAP", "NTCT", "NTFL", "NTGL", "NTGR", "NTIP", "NTNX", "NTO", "NTRS", "NTST", "NTUR", "NTWK", "NUBC", "NUGL", "NVDA", "NVEC", "NVEE", "NVFY", "NVNT", "NVR", "NVTS", "NVVE", "NWAU", "NWBD", "NWBI", "NWFL", "NWGN", "NWL", "NWLI", "NWOL", "NWPP", "NWPX", "NWYF", "NX", "NXDT", "NXPS", "NXRT", "NXTN", "NXTYQ", "NYC", "NYCB", "NYMT", "NZIH", "O", "OABI", "OART", "OBCN", "OBDP", "OBLG", "OBNK", "OBT", "OC", "OCC", "OCCI", "OCFC", "OCLN", "OCN", "OCSL", "ODFL", "ODP", "OEDVQ", "OESX", "OFC", "OFED", "OFLX", "OFS", "OFSI", "OGNT", "OGSM", "OHBK", "OHI", "OICT", "OIG", "OII", "OIS", "OKE", "OKTA", "OLB", "OLED", "OLLI", "OLNK", "OLO", "OLP", "OMAGQ", "OMEX", "OMF", "OMIC", "OML", "OMQS", "OMTK", "OMVE", "ON", "ONB", "ONDS", "ONEI", "ONEW", "ONL", "ONTF", "ONTO", "ONVC", "OOAG", "OPAD", "OPAL", "OPBK", "OPEN", "OPFI", "OPHC", "OPI", "OPMG", "OPMZ", "OPOF", "OPRT", "OPST", "OPTT", "OPVS", "OPXS", "OPY", "ORBN", "ORBT", "ORC", "ORCC", "ORCL", "ORI", "ORLY", "ORN", "ORPB", "ORRF", "OSBC", "OSCR", "OSG", "OSIS", "OSK", "OSPN", "OSRS", "OSS", "OSTK", "OTCM", "OTIS", "OTTV", "OUST", "OUT", "OUTB", "OVBC", "OVLY", "OVV", "OWL", "OXBC", "OXM", "OXSQ", "OXY", "OZ", "OZK", "OZSC", "PAA", "PABN", "PACB", "PACC", "PACW", "PAG", "PAGP", "PANL", "PANW", "PAR", "PARR", "PATH", "PATI", "PATK", "PAWH", "PAY", "PAYA", "PAYC", "PAYD", "PAYO", "PAYS", "PAYX", "PB", "PBAJ", "PBAM", "PBBK", "PBCO", "PBF", "PBFS", "PBHC", "PBHG", "PBI", "PBIO", "PBIT", "PBNK", "PBPB", "PBT", "PCAR", "PCB", "PCH", "PCLB", "PCLI", "PCMC", "PCOA", "PCOK", "PCOR", "PCSB", "PCST", "PCSV", "PCTI", "PCTY", "PCYG", "PD", "PDCE", "PDER", "PDFS", "PDGO", "PDLB", "PDM", "PDNLB", "PEAK", "PEB", "PEBC", "PEBK", "PEBO", "PECO", "PED", "PEGA", "PEGY", "PEI", "PENN", "PERT", "PESI", "PET", "PETS", "PEV", "PFBC", "PFBX", "PFC", "PFG", "PFHD", "PFIE", "PFIN", "PFIS", "PFLC", "PFLT", "PFMT", "PFS", "PFSI", "PFSW", "PFTI", "PFX", "PGAI", "PGC", "PGIE", "PGNN", "PGNT", "PGPM", "PGR", "PGRE", "PGSC", "PGTI", "PGTK", "PGYC", "PH", "PHGD", "PHIG", "PHIL", "PHM", "PHOT", "PHUN", "PHX", "PI", "PIAC", "PII", "PIK", "PINE", "PIPR", "PIXY", "PJET", "PJT", "PK", "PKBK", "PKDC", "PKE", "PKI", "PKIN", "PKKW", "PKOH", "PL", "PLAB", "PLAY", "PLBC", "PLBY", "PLCE", "PLD", "PLFF", "PLFX", "PLMR", "PLNT", "PLNTQ", "PLOW", "PLPC", "PLTR", "PLUG", "PLUS", "PLWN", "PLXS", "PLYM", "PMAH", "PMBY", "PMDP", "PMHG", "PMSO", "PMT", "PMTS", "PMXX", "PNBI", "PNBK", "PNC", "PNFP", "PNGB", "PNNT", "PNPL", "PNRC", "PNRG", "POGS", "POL", "POLA", "POLR", "POOL", "POSH", "POWI", "POWL", "POWW", "PPBI", "PPBN", "PPHC", "PPHI", "PPIH", "PPMH", "PPRW", "PPSI", "PQE", "PR", "PRA", "PRAA", "PRCH", "PRCX", "PRDO", "PRFT", "PRG", "PRGS", "PRHB", "PRI", "PRIM", "PRK", "PRKA", "PRKR", "PRLB", "PRLE", "PRO", "PROV", "PRPL", "PRPM", "PRRE", "PRRY", "PRSI", "PRSO", "PRST", "PRT", "PRTH", "PRTS", "PRTY", "PRU", "PRVU", "PRXIQ", "PRXM", "PRZM", "PSA", "PSBC", "PSBP", "PSBQ", "PSCO", "PSEC", "PSIX", "PSN", "PSNL", "PSSR", "PSTG", "PSTL", "PSTRQ", "PSWR", "PSX", "PTBS", "PTC", "PTCP", "PTEN", "PTLO", "PTMN", "PTOI", "PTON", "PTRA", "PTRC", "PTRO", "PTRS", "PTSI", "PTTL", "PTTN", "PUGE", "PUMP", "PUPS", "PURA", "PVBC", "PVBK", "PVH", "PVL", "PVNO", "PVRS", "PVS", "PW", "PWBO", "PWEI", "PWFL", "PWNX", "PWOD", "PWP", "PWR", "PWSC", "PX", "PXD", "PXFG", "PXHI", "PXLW", "PYCR", "PYPL", "PZZA", "QBAK", "QCCO", "QCOM", "QCRH", "QEDN", "QEPC", "QGSI", "QHYG", "QIND", "QLYS", "QMCI", "QMCO", "QMDT", "QNBC", "QNGY", "QNTO", "QNXC", "QOWI", "QPRC", "QRHC", "QRTEA", "QRVO", "QS", "QSEP", "QSI", "QTEK", "QTRX", "QTWO", "QUAD", "QUBT", "QUCT", "QUGB", "QUIK", "QUMU", "QUOT", "R", "RAFI", "RAGL", "RAIL", "RAMP", "RAND", "RAVE", "RBB", "RBBN", "RBC", "RBCAA", "RBCN", "RBKB", "RBT", "RC", "RCG", "RCII", "RCKY", "RCL", "RCMT", "RCRT", "RCTC", "RDAR", "RDFN", "RDN", "RDVT", "RDW", "RDWD", "REAL", "REATO", "REDW", "REFI", "REFR", "REG", "REGX", "REI", "REKR", "RELI", "RELL", "RELY", "RENO", "RENT", "REOS", "REPO", "REPX", "RES", "REVG", "REX", "REXR", "REZI", "RF", "RFII", "RFIL", "RFL", "RGA", "RGBD", "RGDXQ", "RGEN", "RGGI", "RGP", "RGR", "RGS", "RGST", "RGTI", "RGUS", "RH", "RHI", "RHP", "RHWI", "RIBS", "RICK", "RIDE", "RIHT", "RIII", "RILY", "RIOT", "RITM", "RIVN", "RIVT", "RIVU", "RJF", "RKFL", "RKLB", "RKT", "RL", "RLBY", "RLGT", "RLI", "RLJ", "RM", "RMAX", "RMBI", "RMBL", "RMBS", "RMNI", "RMR", "RNG", "RNGR", "RNST", "RNWF", "RNWK", "RNWR", "ROAD", "ROBK", "ROCC", "ROCK", "ROG", "ROIC", "ROK", "ROL", "ROOT", "ROP", "ROST", "ROVR", "ROWC", "ROYE", "ROYL", "ROYTL", "RPAY", "RPD", "RPDT", "RPID", "RPMT", "RPT", "RRBI", "RRC", "RRGB", "RRR", "RRTS", "RRX", "RSCF", "RSG", "RSI", "RSKIA", "RSRV", "RSSS", "RSTN", "RTL", "RTME", "RTNB", "RTON", "RTSO", "RTX", "RUN", "RUN.H", "RUNI", "RUSHA", "RUTH", "RVIC", "RVLV", "RVRF", "RVS", "RVSB", "RVTI", "RVYL", "RWAY", "RWCB", "RWCI", "RWFC", "RWGI", "RWT", "RWWI", "RXO", "RXT", "RYAN", "RYN", "RYPE", "S", "SABK", "SABR", "SACH", "SAFE", "SAFS", "SAFT", "SAH", "SAI", "SAIA", "SAIC", "SAL", "SAMG", "SANM", "SANT", "SAR", "SASI", "SASR", "SATL", "SAVE", "SAVW", "SBAC", "SBCF", "SBFG", "SBH", "SBIG", "SBKO", "SBNC", "SBNY", "SBOW", "SBR", "SBRA", "SBSI", "SBT", "SBUX", "SCBS", "SCDA", "SCFR", "SCGX", "SCGY", "SCHW", "SCI", "SCIA", "SCKT", "SCM", "SCNG", "SCOO", "SCPT", "SCRH", "SCS", "SCSC", "SCTN", "SCTY", "SCU", "SCVL", "SCWO", "SCWX", "SCX", "SCYT", "SCZC", "SD", "SDCH", "SDIG", "SDPI", "SDTTU", "SEAC", "SEAS", "SEAT", "SEBC", "SECI", "SEDN", "SEER", "SEIC", "SELF", "SEMR", "SENR", "SES", "SEVN", "SEYE", "SF", "SFBC", "SFBE", "SFBI", "SFBS", "SFDL", "SFE", "SFIGA", "SFIX", "SFLM", "SFNC", "SFPI", "SFRX", "SFST", "SFT", "SG", "SGBX", "SGC", "SGH", "SGLS", "SGLY", "SGMA", "SGTB", "SHAK", "SHBI", "SHC", "SHFS", "SHLS", "SHO", "SHOO", "SHPW", "SHRG", "SHYF", "SI", "SIDU", "SIEB", "SIF", "SIGI", "SIII", "SIMC", "SIMPQ", "SIRC", "SITC", "SITE", "SITM", "SITOQ", "SIVB", "SIX", "SIXD", "SJT", "SKAS", "SKIL", "SKPI", "SKT", "SKTP", "SKVY", "SKX", "SKY", "SKYF", "SKYH", "SKYT", "SKYW", "SKYX", "SLAB", "SLB", "SLCA", "SLDP", "SLG", "SLGC", "SLLN", "SLM", "SLNG", "SLNH", "SLOT", "SLQT", "SLRC", "SLRK", "SLTZ", "SLUP", "SM", "SMAA", "SMAR", "SMBC", "SMBK", "SMCI", "SMFX", "SMGI", "SMHI", "SMIT", "SMLP", "SMME", "SMMF", "SMP", "SMPP", "SMR", "SMRL", "SMRT", "SMSI", "SMTC", "SNA", "SNBR", "SNCE", "SNCR", "SNCY", "SND", "SNDR", "SNDZ", "SNEX", "SNFCA", "SNGY", "SNHO", "SNLC", "SNMN", "SNMP", "SNOW", "SNPO", "SNPS", "SNRR", "SNSGF", "SNTX", "SNV", "SNVP", "SNX", "SOBR", "SOBS", "SODI", "SOEN", "SOFI", "SOFO", "SOHI", "SOHO", "SOI", "SOIS", "SOL", "SOLS", "SOM", "SOMC", "SOME", "SOND", "SONM", "SONO", "SOR", "SOTK", "SOUN", "SOYO", "SP", "SPCE", "SPDC", "SPFI", "SPFX", "SPG", "SPGI", "SPGZ", "SPI", "SPIR", "SPLK", "SPLM", "SPLP", "SPMI", "SPND", "SPOI", "SPR", "SPRN", "SPRS", "SPRU", "SPSC", "SPSY", "SPT", "SPWH", "SPWR", "SPXC", "SQ", "SQCC", "SQCF", "SQFT", "SQL", "SQSP", "SRAX", "SRBT", "SRC", "SRCE", "SRCL", "SRG", "SRI", "SRNN", "SRNW", "SRPX", "SRSN", "SRT", "SRYB", "SSB", "SSBI", "SSBK", "SSBP", "SSCC", "SSD", "SSFT", "SSHT", "SSIC", "SSNC", "SSNT", "SSSS", "SSTI", "SSYS", "ST", "STAF", "STAG", "STAR", "STBA", "STBI", "STC", "STCB", "STCN", "STDE", "STEL", "STEM", "STEP", "STER", "STHI", "STJO", "STKS", "STOR", "STR", "STRA", "STRB", "STRC", "STRI", "STRL", "STRS", "STRT", "STSC", "STSFF", "STT", "STTX", "STWC", "STWD", "STYS", "SUI", "SUIC", "SUMO", "SUN", "SUND", "SUNL", "SUNW", "SUP", "SVC", "SVRS", "SVSE", "SVT", "SVVC", "SVXA", "SWBI", "SWCC", "SWCH", "SWI", "SWIM", "SWIOU", "SWK", "SWKH", "SWKS", "SWN", "SWRL", "SWRM", "SXI", "SYBT", "SYF", "SYNA", "SYNE", "SYNH", "SYPR", "SYSX", "SZL", "TA", "TACT", "TAER", "TAIT", "TAL", "TALN", "TALO", "TAMG", "TASK", "TAST", "TAYD", "TBBA", "TBBK", "TBI", "TBK", "TBLT", "TBNK", "TBTC", "TCBC", "TCBI", "TCBK", "TCBS", "TCBX", "TCCO", "TCEC", "TCFC", "TCI", "TCOR", "TCPC", "TCS", "TDC", "TDCB", "TDG", "TDRK", "TDUP", "TDW", "TDY", "TEAM", "TECH", "TEGR", "TEKI", "TELL", "TENB", "TER", "TESS", "TETAA", "TEX", "TFC", "TFRY", "TFSL", "TGAN", "TGEN", "TGHI", "TGI", "TGIC", "TGRO", "TGT", "TH", "THFF", "THG", "THO", "THR", "THRM", "THVB", "TIDE", "TIG", "TIGE", "TIKK", "TILE", "TIPT", "TISDZ", "TISI", "TITN", "TJX", "TKLS", "TKNO", "TKOI", "TKR", "TLF", "TLS", "TLSS", "TLYS", "TMAK", "TMEB", "TMEN", "TMHC", "TMMI", "TMNA", "TMO", "TMP", "TMSH", "TMXN", "TNA", "TNC", "TNEN", "TNET", "TNL", "TNLX", "TNTRQ", "TOL", "TOMZ", "TOST", "TOWN", "TPC", "TPCS", "TPG", "TPH", "TPHS", "TPIC", "TPL", "TPR", "TPRP", "TPVG", "TPX", "TRAC", "TRBD", "TRBK", "TRC", "TRCK", "TRCY", "TREE", "TREP", "TREX", "TRGP", "TRIN", "TRIQ", "TRMB", "TRMK", "TRN", "TRNO", "TRNS", "TROW", "TRSI", "TRST", "TRT", "TRTI", "TRTX", "TRU", "TRUP", "TRUX", "TRV", "TRVR", "TRXO", "TSBA", "TSBK", "TSCC", "TSCO", "TSLA", "TSLX", "TSP", "TSRI", "TSSI", "TSSP", "TSYI", "TTC", "TTCM", "TTEC", "TTEK", "TTI", "TTMI", "TTNN", "TTSH", "TUEM", "TUP", "TURN", "TUSK", "TUXS", "TVNB", "TVOG", "TVPC", "TW", "TWAC", "TWCF", "TWI", "TWIN", "TWKS", "TWLO", "TWNE", "TWO", "TWOU", "TXG", "TXHE", "TXHG", "TXMC", "TXN", "TXRH", "TXT", "TYBT", "TYCB", "TYFG", "TYL", "U", "UAA", "UAL", "UAPC", "UATG", "UAVS", "UBA", "UBAB", "UBCP", "UBER", "UBFO", "UBNC", "UBOH", "UBSI", "UCBI", "UCIX", "UCPC", "UCTT", "UDMY", "UDR", "UDSG", "UE", "UEC", "UEIC", "UFAB", "UFCS", "UFI", "UFMG", "UFPI", "UGE", "UGRO", "UHAL", "UHT", "UI", "UIHC", "UIS", "UITA", "UK", "ULBI", "ULCC", "ULFS", "ULH", "ULTA", "UMAV", "UMAX", "UMBF", "UMH", "UMLS", "UMPQ", "UNAM", "UNB", "UNDR", "UNF", "UNIB", "UNIF", "UNIR", "UNIT", "UNM", "UNP", "UNPA", "UNRG", "UNTC", "UNTN", "UNTY", "UNVR", "UNXLQ", "UP", "UPIN", "UPLD", "UPS", "UPST", "UPWK", "URAL", "URBN", "URE", "URI", "USAC", "USAE", "USAM", "USB", "USCB", "USDP", "USEG", "USEI", "USER", "USIO", "USLQ", "USRI", "USX", "UTGN", "UTI", "UTRX", "UUU", "UUUU", "UVE", "UVSE", "UVSP", "UWHR", "UWKI", "UWMC", "V", "VABK", "VAC", "VALU", "VATE", "VBFC", "VBTC", "VBTX", "VC", "VCON", "VCSA", "VCST", "VCTL", "VCTR", "VCTY", "VCYE", "VECO", "VEEE", "VEL", "VERB", "VERI", "VERX", "VERY", "VFC", "VGID", "VHC", "VHLD", "VIAV", "VICI", "VICR", "VIDE", "VIEW", "VINO", "VIRC", "VIRT", "VISL", "VISM", "VIVC", "VIVK", "VKIN", "VLCN", "VLD", "VLDR", "VLO", "VLTA", "VLY", "VMI", "VMTG", "VMW", "VNCE", "VNJA", "VNO", "VNOM", "VNT", "VNTN", "VOC", "VORB", "VOXX", "VOYA", "VOYT", "VPER", "VPG", "VRA", "VRAR", "VRCM", "VRE", "VRM", "VRME", "VRNS", "VRNT", "VRRM", "VRSK", "VRSN", "VRT", "VRTB", "VRTC", "VRTS", "VRTV", "VRY", "VSAT", "VSCO", "VSEC", "VSH", "VSMR", "VSPC", "VSR", "VSST", "VSTO", "VSYM", "VTDRF", "VTEQ", "VTMC", "VTNA", "VTNR", "VTOL", "VTR", "VTSI", "VTXB", "VUOC", "VUZI", "VVI", "VVNT", "VVX", "VYEY", "VZIO", "W", "WAB", "WABC", "WAFD", "WAKE", "WAL", "WARM", "WASH", "WAT", "WATR", "WATT", "WAVD", "WAYN", "WAYS", "WBBW", "WBHC", "WBS", "WBSR", "WCC", "WCCP", "WCFB", "WCRS", "WCYN", "WD", "WDAY", "WDC", "WDFN", "WDLF", "WDRP", "WE", "WEAV", "WEBR", "WELL", "WELX", "WEN", "WERN", "WERU", "WES", "WEX", "WEYS", "WFC", "WFCF", "WFRD", "WGEI", "WGNR", "WGO", "WH", "WHD", "WHEN", "WHF", "WHG", "WHLM", "WHLR", "WHR", "WINA", "WING", "WINR", "WINSF", "WIRE", "WIRX", "WISA", "WISH", "WK", "WKHS", "WLDN", "WLFC", "WLMS", "WLYW", "WM", "WMB", "WMC", "WMPN", "WMS", "WNC", "WNDW", "WNEB", "WNWG", "WOAM", "WODI", "WOFA", "WOLF", "WOOF", "WORC", "WOWI", "WPC", "WPFH", "WRAP", "WRB", "WRBY", "WRLC", "WRLD", "WSBC", "WSBF", "WSC", "WSCO", "WSFGQ", "WSFL", "WSFS", "WSHE", "WSM", "WSO", "WSR", "WST", "WSTL", "WSTN", "WT", "WTBA", "WTBFB", "WTECQ", "WTFC", "WTI", "WTLC", "WTM", "WTRO", "WTS", "WTT", "WTTR", "WU", "WULF", "WVFC", "WW", "WWD", "WWNG", "WWR", "WWW", "WY", "WYNN", "WYY", "XBOR", "XCLL", "XCOMQ", "XCPL", "XCPT", "XDSL", "XELA", "XELB", "XERI", "XHR", "XLPI", "XM", "XMEX", "XMTR", "XNNHQ", "XOM", "XOS", "XPEL", "XPER", "XPO", "XPOF", "XPON", "XREG", "XRX", "XSPT", "XSVT", "XTMM", "XWEL", "XYL", "XYNH", "YAYO", "YDVL", "YELL", "YETI", "YEXT", "YOSH", "YOU", "YPPN", "YRIV", "YTY", "YUANF", "YUM", "YUMAQ", "ZAZA", "ZBRA", "ZDPY", "ZEON", "ZEST", "ZETA", "ZEV", "ZFOX", "ZG", "ZION", "ZM", "ZMA", "ZNOG", "ZNRG", "ZRFY", "ZS", "ZTNO", "ZUMZ", "ZUO", "ZVOI", "ZWS")

In [362]:
# CHANGE ME
# DATE RANGE
start_date = ('2019-01-01')
end_date = ('2021-12-01')

In [363]:
# DON'T CHANGE ME
params = {'tickers': tickers_compiled, 'start_date': start_date, 'end_date': end_date}

In [364]:
# Financial Ratios: change the first line in SELECT ...... to include more ratios
# start date and end date can be changed above

data_ratios = db.raw_sql(
    """
    SELECT TICKER, public_date as date, bm as book_to_market, capital_ratio, evm as enterprise_value_multiple, ptb as price_to_book, 
    roe as return_on_equity, invt_act as inventory_current_asset_frac, rect_act as receivable_current_asset_frac, cash_ratio, efftax as effective_tax_rate, debt_assets 
    FROM wrdsapps_finratio.firm_ratio 
    WHERE TICKER IN %(tickers)s AND public_date >= %(start_date)s AND public_date <= %(end_date)s
    """,
params=params)

In [365]:
tables = db.list_tables("wrdsapps")
# check whether the table contains m_stock
#print(db.describe_table(library='wrdsapps_beta', table='betasuite'))
#print(tables)

In [366]:
# company monthly stock data
data_price = db.raw_sql(
    """
    SELECT Ticker as Ticker, MthCalDt as Date, ICBIndustry as ICB_industry_code, MthRet as monthly_return, sprtrn as snp_monthly_return, MthCap as monthly_mktcap, MthPrcVol as monthly_price_volume
    FROM crspm.wrds_msfv2_query
    WHERE Ticker in %(tickers)s AND MthCalDt >= %(start_date)s AND MthCalDt <= %(end_date)s
    """, 
    params=params)

In [367]:
db.describe_table(library='crspm', table='mcti')

Approximately 1163 rows in crspm.mcti.

      name  nullable              type comment
0    caldt      True              DATE    None
1   b30ret      True  DOUBLE_PRECISION    None
2   b30ind      True  DOUBLE_PRECISION    None
3   b20ret      True  DOUBLE_PRECISION    None
4   b20ind      True  DOUBLE_PRECISION    None
5   b10ret      True  DOUBLE_PRECISION    None
6   b10ind      True  DOUBLE_PRECISION    None
7    b7ret      True  DOUBLE_PRECISION    None
8    b7ind      True  DOUBLE_PRECISION    None
9    b5ret      True  DOUBLE_PRECISION    None
10   b5ind      True  DOUBLE_PRECISION    None
11   b2ret      True  DOUBLE_PRECISION    None
12   b2ind      True  DOUBLE_PRECISION    None
13   b1ret      True  DOUBLE_PRECISION    None
14   b1ind      True  DOUBLE_PRECISION    None
15  t90ret      True  DOUBLE_PRECISION    None
16  t90ind      True  DOUBLE_PRECISION    None
17  t30ret      True  DOUBLE_PRECISION    None
18  t30ind      True  DOUBLE_PRECISION    None
19  cpiret      True  DOUBLE_PRECISION    None
20  cpiind      True  DOUBLE_PRECISION    None

In [368]:
# Bonds
data_bond = db.raw_sql(
    """
    SELECT caldt as date, b10ret as ten_yr_YTM_rf
    FROM crspm.mcti
    WHERE caldt >= %(start_date)s AND caldt <= %(end_date)s
    """,
    params=params)

In [369]:
data_bond

          date  ten_yr_ytm_rf
0   2019-01-31       0.007138
1   2019-02-28      -0.004272
2   2019-03-29       0.029419
3   2019-04-30      -0.006214
4   2019-05-31       0.031854
5   2019-06-28       0.012073
6   2019-07-31       0.003435
7   2019-08-30       0.040344
8   2019-09-30      -0.013852
9   2019-10-31      -0.000742
10  2019-11-29      -0.007410
11  2019-12-31      -0.011292
12  2020-01-31       0.039182
13  2020-02-28       0.029902
14  2020-03-31       0.039709
15  2020-04-30       0.005024
16  2020-05-29       0.000713
17  2020-06-30       0.000388
18  2020-07-31       0.012821
19  2020-08-31      -0.014709
20  2020-09-30       0.002560
21  2020-10-30      -0.017310
22  2020-11-30       0.004016
23  2020-12-31      -0.004965
24  2021-01-29      -0.010713
25  2021-02-26      -0.025385
26  2021-03-31      -0.029342
27  2021-04-30       0.011851
28  2021-05-28       0.003441
29  2021-06-30       0.014084
30  2021-07-30       0.023829
31  2021-08-31      -0.004837
32  2021-09-30      -0.015425
33  2021-10-29      -0.004896
34  2021-11-30       0.012455

In [370]:
data_ratios
# change piubli

,ticker,date,book_to_market,capital_ratio,enterprise_value_multiple,price_to_book,return_on_equity,inventory_current_asset_frac,receivable_current_asset_frac,cash_ratio,effective_tax_rate,debt_assets
0,AIR,2019-01-31,0.617035,0.177049,12.598434,1.397717,0.084956,0.567395,0.237934,0.122574,0.045337,0.398566
1,AIR,2019-02-28,0.617035,0.177049,12.598434,1.355058,0.084956,0.567395,0.237934,0.122574,0.045337,0.398566
2,AIR,2019-03-31,0.617035,0.177049,12.598434,1.204976,0.084956,0.567395,0.237934,0.122574,0.045337,0.398566
3,AIR,2019-04-30,0.702109,0.174534,11.728077,1.316670,0.080274,0.569560,0.256845,0.131268,0.045337,0.404429
4,AIR,2019-05-31,0.702109,0.174534,11.728077,1.173189,0.080274,0.569560,0.256845,0.131268,0.045337,0.404429
...,...,...,...,...,...,...,...,...,...,...,...,...
64713,PFIE,2019-09-30,0.664596,0.000689,12.269176,1.889405,0.114122,0.297316,0.225908,3.506229,0.292742,0.084753
64714,PFIE,2019-10-31,0.664596,0.000689,12.269176,1.759446,0.114122,0.297316,0.225908,3.506229,0.292742,0.084753
64715,PFIE,2019-11-30,0.539612,0.001019,12.115281,1.395549,0.095578,0.299359,0.221084,3.388938,0.292742,0.085118
64716,PFIE,2019-12-31,0.539612,0.001019,12.115281,1.415575,0.095578,0.299359,0.221084,3.388938,0.292742,0.085118
64717,PFIE,2020-01-31,0.539612,0.001019,12.115281,1.356999,0.095578,0.299359,0.221084,3.388938,0.292742,0.085118

In [371]:
# ESG Data Processing
# read in ESG data
esg_score_raw = pd.read_excel('./Archived Data/ESG_Score_Raw.xlsx')

In [372]:
esg_score_raw.head()

,institutionid,Score Date,Aspect Name,Score Value,Ticker,Company Name
0,100003,2021-01-22,S&P Global ESG Score,14,BOKF,BOK Financial Corporation
1,100003,2020-04-01,S&P Global ESG Score,26,BOKF,BOK Financial Corporation
2,100003,2019-03-21,Social Dimension,22,BOKF,BOK Financial Corporation
3,100003,2021-01-22,Environmental Dimension,25,BOKF,BOK Financial Corporation
4,100003,2021-01-22,Social Dimension,6,BOKF,BOK Financial Corporation

In [373]:
# re-arrange so that company name goes first, and ticker follows, the Score Data, Aspect Name, Socre Value, and institutionid
esg_score_raw = esg_score_raw[['Company Name', 'Ticker', 'Score Date', 'Aspect Name', 'Score Value', 'institutionid']]
# Movie values of aspect name to columns
esg_score_raw = esg_score_raw.pivot_table(index=['Company Name', 'Ticker', 'Score Date', 'institutionid'], columns='Aspect Name', values='Score Value')
# sort by score date
esg_score_raw = esg_score_raw.sort_values(by=['Score Date'])

In [374]:
esg_score_raw = esg_score_raw.sort_values(by=['Score Date'])
esg_score_finished = esg_score_raw.reset_index()
esg_score_finished.head()

Aspect Name,Company Name,Ticker,Score Date,institutionid,Economic Governance Dimension,Environmental Dimension,S&P Global ESG Score,Social Dimension
0,Amdocs Limited,DOX,2019-02-14,4103358,33.5,48.0,35.5,29.5
1,Splunk Inc.,SPLK,2019-02-14,4279508,32.5,11.0,23.0,13.0
2,"Fortinet, Inc.",FTNT,2019-02-14,4868602,34.5,11.0,24.0,12.5
3,Pick n Pay Stores Limited,PIK,2019-02-14,4408268,42.5,39.5,38.0,30.0
4,Dis-Chem Pharmacies Limited,DCP,2019-02-14,4237418,23.5,23.5,22.0,19.5

In [375]:
# rename Ticker to ticker, Score Date to date
esg_score_finished = esg_score_finished.rename(columns={'Ticker': 'ticker', 'Score Date': 'date'})
esg_score_finished.head()

Aspect Name,Company Name,ticker,date,institutionid,Economic Governance Dimension,Environmental Dimension,S&P Global ESG Score,Social Dimension
0,Amdocs Limited,DOX,2019-02-14,4103358,33.5,48.0,35.5,29.5
1,Splunk Inc.,SPLK,2019-02-14,4279508,32.5,11.0,23.0,13.0
2,"Fortinet, Inc.",FTNT,2019-02-14,4868602,34.5,11.0,24.0,12.5
3,Pick n Pay Stores Limited,PIK,2019-02-14,4408268,42.5,39.5,38.0,30.0
4,Dis-Chem Pharmacies Limited,DCP,2019-02-14,4237418,23.5,23.5,22.0,19.5

In [376]:
# merge ESG data with financial ratios based on ticker and date
# change the date column in data_price and data_ratios to date format
data_price['date'] = pd.to_datetime(data_price['date'])
data_ratios['date'] = pd.to_datetime(data_ratios['date'])

# merge data_price and data_ratios
data_price_ratios = pd.merge(data_price, data_ratios, on=['ticker', 'date'], how='inner')

In [377]:
data_price_ratios

,ticker,date,icb_industry_code,monthly_return,snp_monthly_return,monthly_mktcap,monthly_price_volume,book_to_market,capital_ratio,enterprise_value_multiple,price_to_book,return_on_equity,inventory_current_asset_frac,receivable_current_asset_frac,cash_ratio,effective_tax_rate,debt_assets
0,PLXS,2019-01-31,TECH,0.098669,0.078684,1.734894e+06,2.402092e+08,0.502200,0.165804,11.391232,1.854472,0.013296,0.523574,0.260241,0.403547,0.878822,0.523376
1,ORCL,2019-01-31,TECH,0.116883,0.078684,1.802714e+08,1.566963e+10,0.172629,0.573787,14.980523,5.896618,0.081640,0.006440,0.063704,3.208736,0.695993,0.685688
2,MSFT,2019-01-31,TECH,0.028158,0.078684,8.012092e+08,7.427279e+10,0.100123,0.501240,17.537912,9.110448,0.220349,0.015746,0.120804,2.487240,0.545676,0.679475
3,TROW,2019-01-31,FINL,0.012348,0.078684,2.224993e+07,3.465090e+09,0.243912,0.000000,10.937535,3.443995,0.313699,NaN,NaN,NaN,0.368808,0.123917
4,HON,2019-01-31,INDL,0.087118,0.078684,1.063276e+08,8.439477e+09,0.163528,0.423171,14.533619,5.278374,0.122764,0.186726,0.338926,0.579324,0.753984,0.705008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42683,FAF,2021-11-30,FINL,0.014219,-0.008334,8.142516e+06,8.253882e+08,0.799661,0.218494,4.519498,1.382817,0.240363,NaN,NaN,NaN,0.241288,0.649901
42684,SIX,2021-11-30,CONDIS,-0.110868,-0.008334,3.144398e+06,1.460208e+09,NaN,1.679762,17.090495,NaN,NaN,0.149520,0.212416,0.424079,NaN,1.211510
42685,VPG,2021-11-30,INDL,0.007040,-0.008334,4.326610e+05,3.190483e+07,0.587191,0.213888,11.592114,1.555232,0.054501,0.318559,0.219521,1.728939,0.410126,0.376557
42686,CBOE,2021-11-30,FINL,-0.019121,-0.008334,1.375055e+07,1.761450e+09,0.294569,0.282813,14.033437,3.534028,0.119544,0.000000,0.182439,0.997300,0.291036,0.513650
42687,TSLA,2021-11-30,CONDIS,0.027612,-0.008334,1.149642e+09,7.233859e+11,0.034798,0.284537,98.669229,42.433190,0.160491,0.179643,0.078958,1.102255,0.253033,0.528253

In [378]:
esg_score_finished

Aspect Name,Company Name,ticker,date,institutionid,Economic Governance Dimension,Environmental Dimension,S&P Global ESG Score,Social Dimension
0,Amdocs Limited,DOX,2019-02-14,4103358,33.5,48.0,35.5,29.5
1,Splunk Inc.,SPLK,2019-02-14,4279508,32.5,11.0,23.0,13.0
2,"Fortinet, Inc.",FTNT,2019-02-14,4868602,34.5,11.0,24.0,12.5
3,Pick n Pay Stores Limited,PIK,2019-02-14,4408268,42.5,39.5,38.0,30.0
4,Dis-Chem Pharmacies Limited,DCP,2019-02-14,4237418,23.5,23.5,22.0,19.5
...,...,...,...,...,...,...,...,...
5009,Mercury NZ Limited,MCY,2021-12-20,4218192,32.0,46.0,36.0,25.0
5010,"Diamondback Energy, Inc.",FANG,2021-12-20,4337452,44.0,31.0,33.0,19.0
5011,"Motorola Solutions, Inc.",MSI,2021-12-20,4280272,51.0,47.0,45.0,32.0
5012,Beach Energy Limited,BPT,2021-12-20,4356908,54.0,47.0,56.0,66.0
5013,"ServiceNow, Inc.",NOW,2021-12-20,4587650,49.0,26.0,43.0,47.0

In [379]:
# read in betas
fama_french_betas = pd.read_excel('fama_french_betas.xlsx')
capm_betas = pd.read_excel('capm_beta.xlsx')

In [380]:
data_bond

          date  ten_yr_ytm_rf
0   2019-01-31       0.007138
1   2019-02-28      -0.004272
2   2019-03-29       0.029419
3   2019-04-30      -0.006214
4   2019-05-31       0.031854
5   2019-06-28       0.012073
6   2019-07-31       0.003435
7   2019-08-30       0.040344
8   2019-09-30      -0.013852
9   2019-10-31      -0.000742
10  2019-11-29      -0.007410
11  2019-12-31      -0.011292
12  2020-01-31       0.039182
13  2020-02-28       0.029902
14  2020-03-31       0.039709
15  2020-04-30       0.005024
16  2020-05-29       0.000713
17  2020-06-30       0.000388
18  2020-07-31       0.012821
19  2020-08-31      -0.014709
20  2020-09-30       0.002560
21  2020-10-30      -0.017310
22  2020-11-30       0.004016
23  2020-12-31      -0.004965
24  2021-01-29      -0.010713
25  2021-02-26      -0.025385
26  2021-03-31      -0.029342
27  2021-04-30       0.011851
28  2021-05-28       0.003441
29  2021-06-30       0.014084
30  2021-07-30       0.023829
31  2021-08-31      -0.004837
32  2021-09-30      -0.015425
33  2021-10-29      -0.004896
34  2021-11-30       0.012455

In [381]:
data_bond['date'] = pd.to_datetime(data_bond['date'])
data_price_ratios['date'] = pd.to_datetime(data_price_ratios['date'])
esg_score_finished['date'] = pd.to_datetime(esg_score_finished['date'])
capm_betas['date'] = pd.to_datetime(capm_betas['date'])
fama_french_betas['date'] = pd.to_datetime(fama_french_betas['date'])

In [382]:
# rename fama-french Ticker Symbol to ticker
fama_french_betas = fama_french_betas.rename(columns={'Ticker Symbol': 'ticker'})

In [383]:
# merge data_price_ratios and esg_score_finished
# change the date column in data_price_ratios and esg_score_finished to year-month format
data_price_ratios['date'] = data_price_ratios['date'].dt.strftime('%Y-%m')
esg_score_finished['date'] = esg_score_finished['date'].dt.strftime('%Y-%m')
data_bond['date'] = data_bond['date'].dt.strftime('%Y-%m')
capm_betas['date'] = capm_betas['date'].dt.strftime('%Y-%m')
fama_french_betas['date'] = fama_french_betas['date'].dt.strftime('%Y-%m')

# merge data_price_ratios and esg_score_finished
data_incomplete = pd.merge(data_price_ratios, esg_score_finished, on=['ticker', 'date'], how='inner')
data_complete_missing_beta = pd.merge(data_incomplete, data_bond, on=['date'], how='left')
# merge data_complete_missing_beta and fama_french_betas
data_complete_missing_capm_beta = pd.merge(data_complete_missing_beta, fama_french_betas, on=['ticker', 'date'], how='inner')
# merge data_complete_missing_beta and capm_betas
data_complete = pd.merge(data_complete_missing_capm_beta, capm_betas, on=['ticker', 'date'], how='inner')

In [384]:
# move 'Company Name' to the first column
cols = list(data_complete.columns.values)
cols.pop(cols.index('Company Name'))
data_complete = data_complete[['Company Name'] + cols]

# delete institutionid
data_complete = data_complete.drop(columns=['institutionid'])

In [385]:
# export to excel
#data_ratios.to_excel('financial_ratios.xlsx')
#esg_score_finished.to_excel('ESG_Score_Processed.xlsx')
#data_complete.to_excel('data_complete.xlsx')

In [386]:
data_complete.columns

Index(['Company Name', 'ticker', 'date', 'icb_industry_code', 'monthly_return',
       'snp_monthly_return', 'monthly_mktcap', 'monthly_price_volume',
       'book_to_market', 'capital_ratio', 'enterprise_value_multiple',
       'price_to_book', 'return_on_equity', 'inventory_current_asset_frac',
       'receivable_current_asset_frac', 'cash_ratio', 'effective_tax_rate',
       'debt_assets', 'Economic Governance Dimension',
       'Environmental Dimension', 'S&P Global ESG Score', 'Social Dimension',
       'ten_yr_ytm_rf', 'b_mkt_fama_french_3fac', 'b_smb_fama_french_3fac',
       'b_hml_fama_french_3fac', 'alpha_fama_french_3fac',
       'excess_return_fama_french_3fac', 'b_mkt_capm_mkt', 'alpha_capm',
       'excess_return_capm'],
      dtype='object')

In [387]:

# DON't mind these data below, just for record keeping
# turn tickers_compiled into a dataframe
#tickers_compiled = pd.DataFrame(tickers_compiled)
# export to txt file
# tickers_compiled.to_excel('tickers_compiled.xlsx')
# VARIABLES 
# variables = ("TICKER", "public_date", "bm", "capital_ratio", "evm", "ptb", "roe")
# LIBRARY
# library = ('wrdsapps_finratio')
# Table
# table = ('firm_ratio')
# date_name
# date_name = ('public_date')
# ticker_name
# ticker_name = ('ticker')
# list tables 
# db.list_tables(library='wrdsapps_finratio')
# Find all the column names in the table
# print(db.describe_table(library='wrdsapps_finratio', table='firm_ratio'))
# Run the following code to see what the schema is for the for any tables in a library
data_test = db.raw_sql(
    """
    SELECT *
    FROM trucost.wrds_esg
    LIMIT 6
    """,
params=params)
data_test.columns()

TypeError: 'Index' object is not callable